#!/usr/bin/env php
<?php

	define('BASE_PATH', __DIR__);
	define('YII_DEBUG', true);
	define('YII_ENV', 'dev');

	// fcgi doesn't have STDIN and STDOUT defined by default
	defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
	defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

	require BASE_PATH.'/../vendor/composer/autoload.php';
	require BASE_PATH.'/../vendor/composer/yiisoft/yii2/Yii.php';
	require BASE_PATH.'/../common/config/bootstrap.php';

	$config = require BASE_PATH.'/../common/config/console.php';

	exit((new yii\console\Application($config))->run());
